#!/bin/sh

PROFILE="default"
case "${1}" in --profile=*) PROFILE="${1#*=}"; shift;; esac

if [ -z "${1}" ]; then
	echo -e "usage: yukon [--profile=PROFILE] APPLICATION <ARGS>\n"
	echo -e "\tYou can use this wrapper script to run any program using the"
	echo -e "\tyukon library."
	echo -e ""
	echo -e "Webpage - http://www.neopsis.com/projects/yukon"
	echo -e "Version - \$Id$"

	exit 1
fi

YLDPATH="${HOME}/.yukon/local"
SYSDIRS="/etc/yukon/system ${HOME}/.yukon/system"
for DIR in ${SYSDIRS}; do
	if [ -d "${DIR}" ]; then
		for FILE in "${DIR}"/*; do
			. "${FILE}"
			YLDPATH="${YLDPATH}:${LDPATH}"
		done
	fi
done

echo "${YLDPATH}:${LD_LIBRARY_PATH}" YUKON="${PROFILE}"
LD_LIBRARY_PATH="${YLDPATH}:${LD_LIBRARY_PATH}" YUKON="${PROFILE}" "${@}"