#!/bin/sh

if [ -z "${1}" ]; then
	echo -e "usage: yukon APPLICATION <ARGS>\n"
	echo -e "\tYou can use this wrapper script to run any program using the"
	echo -e "\tyukon library."
	echo -e ""
	echo -e "Webpage - http://www.neopsis.com/projects/yukon"
	echo -e "Version - \$Id$"

	exit 1
fi

LIBDIR=${LIBDIR:-'lib'}

eval "LD_LIBRARY_PATH=/usr/local/${LIBDIR}/yukon:${LD_LIBRARY_PATH} ${*}"
